### ISSUE TITLE
Error running `yarn install` on Challenge 0. 

### ISSUE THREAD

**Issue by neocybereth** [BuidlGuidl/SpeedRunEthereum#184]
![Screen Shot 2022-12-20 at 1 53 49 PM](https://user-images.githubusercontent.com/14209806/208556278-c6fe9a3e-dd5a-42d3-88ef-fdce9b8550b5.png)

`yarn install` is throwing this error for me. 

As a solution I deleted the `yarn.lock` and re-ran `yarn install` and that did the trick 👍

**Comment by carletex** [comment]
Hey @neocybereth 

Can you post the issue here? https://github.com/scaffold-eth/scaffold-eth-challenges

This repo is just for the site  (frontend & backend) but the challenges are handled in that other repo.

Thanks!
