### ISSUE TITLE
Submit custom branch & "Mentor/Power user" role

### ISSUE THREAD

**Issue by carletex** [BuidlGuidl/SpeedRunEthereum#43]
We want to add a new role (besides user / admin): "Mentor", "PRO User" or whatever.

Users with this role should be able to submit new challenges / branches. We could have a "submit new challenge" button after the challenge list.

**Comment by dgrcode** [comment]
I think this one is complete, right?

**Comment by carletex** [comment]
Not sure. rn we allow submitting new builds, but not new challenges.

I think this is meant for builders who wants to showcase their stuff in their portfolio page (besides pre defined challenges). But we should double check before tackling this one.
