### ISSUE TITLE
External Badge Contract

### ISSUE THREAD

**Issue by simplemachine92** [BuidlGuidl/SpeedRunEthereum#95]
I'm working on this myself, but thought I'd open an issue in case someone can solve faster than myself. We need to call external contract mint functions on "Approve" of user submissions (in challenge-review). A test contract is deployed. 

https://polygonscan.com/address/0x093f2785b8eded6b00fe7a8b2a8aa9197f291147

Anyway, I'll be trying to resolve this myself in the meantime!

**Comment by carletex** [comment]
Hey @simplemachine92 thanks for this!

I'm working on a couple of issues rn. Once I finish, I can help you with this one IYW.
